# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1544, 1222)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_start_omega = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_omega.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_start_omega.setObjectName("btn_start_omega")
        self.horizontalLayout.addWidget(self.btn_start_omega)
        self.btn_start_path = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start_path.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_start_path.setObjectName("btn_start_path")
        self.horizontalLayout.addWidget(self.btn_start_path)
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_pause.setObjectName("btn_pause")
        self.horizontalLayout.addWidget(self.btn_pause)
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_sys_info = QtWidgets.QLabel(self.centralwidget)
        self.label_sys_info.setMinimumSize(QtCore.QSize(0, 60))
        self.label_sys_info.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label_sys_info.setStyleSheet("background-color: #1e3d59; color: #00ffcc; font-size: 16px; font-weight: bold; border-radius: 5px;")
        self.label_sys_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sys_info.setObjectName("label_sys_info")
        self.verticalLayout_2.addWidget(self.label_sys_info)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.container_sofa = QtWidgets.QWidget(self.centralwidget)
        self.container_sofa.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.container_sofa.setObjectName("container_sofa")
        self.horizontalLayout_5.addWidget(self.container_sofa)
        self.container_us = QtWidgets.QWidget(self.centralwidget)
        self.container_us.setObjectName("container_us")
        self.horizontalLayout_5.addWidget(self.container_us)
        self.horizontalLayout_5.setStretch(0, 2)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1544, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_start_omega.setText(_translate("MainWindow", "交互模式"))
        self.btn_start_path.setText(_translate("MainWindow", "预定义模式"))
        self.btn_pause.setText(_translate("MainWindow", "⏸ 暂停"))
        self.btn_stop.setText(_translate("MainWindow", "⏹ 停止"))
        self.label_sys_info.setText(_translate("MainWindow", "系统就绪：等待启动仿真中……"))
